[theme]
base = "dark"
primaryColor = "#2DD4BF"          # Verde Neon (Destaque)
backgroundColor = "#02040A"       # Preto Azulado Profundo (Fundo Principal)
secondaryBackgroundColor = "#1E293B" # Cinza Azulado (Barra Lateral - Mais claro)
textColor = "#F3F4F6"             # Branco Gelo (Texto)
font = "sans serif"
